char *printname[75] = {
/*FIRSTTOKEN*/	"(null)",
/*FINAL*/	"(null)",
/*FATAL*/	"(null)",
/*LT*/	" < ",
/*LE*/	" <= ",
/*GT*/	" > ",
/*GE*/	" >= ",
/*EQ*/	" == ",
/*NE*/	" != ",
/*MATCH*/	" ~ ",
/*NOTMATCH*/	" !~ ",
/*APPEND*/	"(null)",
/*ADD*/	" + ",
/*MINUS*/	" - ",
/*MULT*/	" * ",
/*DIVIDE*/	" / ",
/*MOD*/	" % ",
/*UMINUS*/	" -",
/*ASSIGN*/	" = ",
/*ADDEQ*/	" += ",
/*SUBEQ*/	" -= ",
/*MULTEQ*/	" *= ",
/*DIVEQ*/	" /= ",
/*MODEQ*/	" %= ",
/*JUMP*/	"(null)",
/*XBEGIN*/	"(null)",
/*XEND*/	"(null)",
/*NL*/	"(null)",
/*PRINT*/	"print",
/*PRINTF*/	"printf",
/*SPRINTF*/	"sprintf ",
/*SPLIT*/	"split",
/*IF*/	"if(",
/*ELSE*/	"(null)",
/*WHILE*/	"while(",
/*FOR*/	"for(",
/*IN*/	"instat",
/*NEXT*/	"next",
/*EXIT*/	"exit",
/*BREAK*/	"break",
/*CONTINUE*/	"continue",
/*PROGRAM*/	"(null)",
/*PASTAT*/	"(null)",
/*PASTAT2*/	"(null)",
/*ASGNOP*/	"(null)",
/*BOR*/	" || ",
/*AND*/	" && ",
/*NOT*/	" !",
/*NUMBER*/	"(null)",
/*VAR*/	"(null)",
/*ARRAY*/	"(null)",
/*FNCN*/	"fncn",
/*SUBSTR*/	"substr",
/*LSUBSTR*/	"(null)",
/*INDEX*/	"sindex",
/*RELOP*/	"(null)",
/*MATCHOP*/	"(null)",
/*OR*/	"(null)",
/*STRING*/	"(null)",
/*DOT*/	"(null)",
/*CCL*/	"(null)",
/*NCCL*/	"(null)",
/*CHAR*/	"(null)",
/*CAT*/	" ",
/*STAR*/	"(null)",
/*PLUS*/	"(null)",
/*QUEST*/	"(null)",
/*POSTINCR*/	"++",
/*PREINCR*/	"++",
/*POSTDECR*/	"--",
/*PREDECR*/	"--",
/*INCR*/	"(null)",
/*DECR*/	"(null)",
/*FIELD*/	"(null)",
/*INDIRECT*/	"$(",
};
